#!/bin/bash

if [[ "$BASH_SOURCE" == /* ]]; then
    TOP=$(realpath $(dirname $BASH_SOURCE)/..)
else
    TOP=$(realpath $(pwd)/$(dirname $BASH_SOURCE)/..)
fi


if [[ `uname -a` == *Microsoft* ]]; then
    # wsl
    source $TOP/setup-win.d/10-home.sh
fi
