#!/bin/bash

d=`pwd`/`dirname $0`

if test ! -e $HOME/.bashrc; then
    touch $HOME/.bashrc
fi
echo "source $d/bashrc" >> $HOME/.bashrc

if test ! -e $HOME/.gitconfig; then
    ln -s $d/git/gitconfig  $HOME/.gitconfig
fi

if test ! -e $HOME/.vimrc; then
    ln -s $d/vim/vimrc  $HOME/.vimrc
    ln -s $d/vim/vimrc.vundle   $HOME/.vimrc.vundle
    mkdir $HOME/.vim
    git clone https://github.com/VundleVim/Vendle.vim.git   $HOME/.vim/bundle/Vundle.vim
fi

if test ! -e $HOME/.tmux.conf; then
    ln -s $d/tmux.conf  $HOME/.tmux.conf
fi
