#!/bin/bash

root=$(realpath $(pwd)/$(dirname $0))

if test ! -e $HOME/.bashrc; then
    touch $HOME/.bashrc
fi
echo "source '$root/bashrc'" >> $HOME/.bashrc

if test -d $root/setup.d; then
    bash $root/setup.d/*.sh $root
fi
