#!/bin/bash

if [[ "$BASH_SOURCE" == /* ]]; then
    TOP=$(realpath $(dirname $BASH_SOURCE)/..)
else
    TOP=$(realpath $(pwd)/$(dirname $BASH_SOURCE)/..)
fi


if [[ $OSTYPE == 'darwin'* ]]; then
    source $TOP/setup-mac.d/10-setup.sh
fi
