#!/bin/bash

# .bashrc sourced by interactive & non-login bash

# set prompting; see PROMPTING in bash manual
function bash_ps1() {
    local readonly titlebar="\[\e]2;\u@\h:\w\a\]";
    local readonly prefix="\[\e[32;40m\]----------------------------------------\[\e[m\]\n";
    local readonly workingDir="\[\e[33m\]\w\[\e[0m\]";
    local readonly time="\[\e[37m\]\t\[\e[0m\]";
    local readonly prompt="\[\e[31m\]\$\[\e[0m\] ";
    local readonly user="\[\e[36m\]\u\[\e[0m\]";
    local readonly host="\[\e[32m\]\H\[\e[0m\]";
    case $TERM in
    linux)
        #echo "$prefix$user@$host:$workingDir\n$prompt";
        echo "$user@$host:$workingDir\n$prompt";
    ;;
    *-256color)
        #echo "$prefix$titlebar$workingDir\n$prompt";
        echo "$titlebar$time $user@$host:$workingDir\n$prompt";
    ;;
    esac
}
PS1=`bash_ps1`

# general aliases
alias ..='\cd ..'
alias grep='\grep --color=auto'
alias l='ls'
alias ls='\ls --classify --color=auto --group-directories-first --human-readable --show-control-chars'
alias ll='ls -a -h -l'
alias mv='mv -i'
alias df='df -hPT'
alias du='du -hs'
alias dstat='dstat -cdlmnpsy'
alias cmd='gnome-terminal'
alias chrome='google-chrome'

# disable touchpad
synclient touchpadoff=1 2>/dev/null

# disable auto-mount-open
if test -e "`which gsettings`"; then
    gsettings set "org.gnome.desktop.media-handling" "automount-open" "false"
fi
