source $HOME/.vim/vundle.vim

set nocompatible nobackup
set viminfo= " turn off logging

if has("gui_running") || &t_Co == 256
"    let g:solarized_termcolors=256
"    set background=light
"    colorscheme solarized
    color eclipse-lite
else
    color lamp
endif

set noautoindent
"set ambiwidth=double
set backspace=indent,eol,start
set fencs=utf8,gb2312,gbk,big5,gb18030,iso8859-1
set ffs=unix,dos
set formatoptions=tcqro " add space and asterisk on newline in comment
"filetype indent on
set hlsearch incsearch
set list listchars=tab:>-,trail:=
highlight SpecialKey ctermfg=1
set nolinebreak
set number showmatch
set ruler scrolloff=4 showcmd laststatus=2
set splitright
set tabstop=8 noexpandtab
set textwidth=80 fo="" cc=+0 | hi ColorColumn ctermbg=lightblue
set winaltkeys=no

if has("autocmd")
"set autochdir
autocmd BufReadPost * cd %:p:h " goto file's dirname before open it
autocmd FileType c,cpp,java,html,css,javascript,xml,php,sh,python,vim   :set ts=4 sw=4 et fo=""
autocmd FileType make   :set ts=8 sw=8 noet
autocmd FileType rfc    :set ts=3 et tw=72 fo="tcq"
autocmd BufWritePre *.html,*.css,*.js,*.php,*.xml,*.py,*.sh,*.c,*.cpp,*.h,*.java %s/\s\+$//e " trailing space
endif

" fctix.vim
set ttimeoutlen=100

inoremap    jk  <esc>

" move around
inoremap    <c-a>   <home>
inoremap    <c-e>   <end>

" edit
inoremap    <c-d>   <esc>ddi
nnoremap    <c-d>   dd
inoremap    <c-u>   <esc>ld<home><esc>i
inoremap    <c-k>   <esc>ld<end><esc>a

" tab/window switch
nnoremap    <m-1>   1gt
nnoremap    <m-2>   2gt
nnoremap    <m-3>   3gt
nnoremap    <m-4>   4gt

" misc
inoremap    <F2>    <C-R>=strftime("%Y-%m-%d %H:%M:%S %z")<CR>
inoremap    <c-u>   <c-\><c-o>d<home>
inoremap    <c-k>   <c-\><c-o>d<end>
inoremap    <C-s>   <Esc>:w<CR>a
