set nocompatible nobackup

set backspace=indent,eol,start
set fencs=utf8,gb2312,gbk,big5,gb18030,iso8859-1 ffs=unix,dos
set number ruler showcmd laststatus=2 scrolloff=4 hlsearch incsearch splitright showmatch

if has("gui_running") || &t_Co == 256
    syntax on | color ron
"    let g:solarized_termcolors=256
"    set background=light
"    color solarized
else
endif

" disable logging
set viminfo=



set noautoindent

" add space and asterisk on newline in comment
set formatoptions=tcqro

highlight SpecialKey ctermfg=1
set list listchars=tab:>-,trail:=

set nolinebreak nobreakindent

set textwidth=80 fo="" cc=+0 | hi ColorColumn ctermbg=lightblue

set tabstop=8 noexpandtab



if has("autocmd")
"set autochdir
autocmd BufReadPost * cd %:p:h " goto file's dirname before open it
autocmd FileType c,cpp,java,html,css,javascript,xml,php,sh,python,vim,lua   :set ts=4 sw=4 et fo=""
autocmd FileType make   :set ts=8 sw=8 noet
autocmd FileType rfc    :set ts=3 et tw=72 fo="tcq"
autocmd BufWritePre *.html,*.css,*.js,*.php,*.xml,*.py,*.sh,*.c,*.cpp,*.h,*.java,*.lua %s/\s\+$//e " trailing space
endif

" fctix.vim
set ttimeoutlen=100

set winaltkeys=no

inoremap    jk  <esc>

" move around
inoremap    <c-a>   <home>
inoremap    <c-e>   <end>

" edit
inoremap    <c-d>   <esc>ddi
nnoremap    <c-d>   dd
inoremap    <c-u>   <esc>ld<home><esc>i
inoremap    <c-k>   <esc>ld<end><esc>a

" tab/window switch
nnoremap    <m-1>   1gt
nnoremap    <m-2>   2gt
nnoremap    <m-3>   3gt
nnoremap    <m-4>   4gt

" misc
inoremap    <F2>    <C-R>=strftime("%Y-%m-%d %H:%M:%S %z")<CR>
inoremap    <c-u>   <c-\><c-o>d<home>
inoremap    <c-k>   <c-\><c-o>d<end>
inoremap    <c-s>   <Esc>:w<CR>a
